package kinoko.packet.stage;

public enum LoginResult {
    SUCCESS(0),
    TEMP_BLOCKED(1),
    BLOCKED(2),
    ABANDONED(3),
    INCORRECT_PASSWORD(4),
    NOT_REGISTERED(5),
    DB_FAIL(6),
    ALREADY_CONNECTED(7),
    NOT_CONNECTABLE_WORLD(8),
    UNKNOWN(9),
    TIMEOUT(10),
    NOT_ADULT(11),
    AUTH_FAIL(12),
    IMPOSSIBLE_IP(13),
    NOT_AUTHORIZED_NEXON_ID(14),
    NO_NEXON_ID(15),
    NOT_AUTHORIZED(16),
    INVALID_REGION_INFO(17),
    INVALID_BIRTH_DATE(18),
    PASSPORT_SUSPENDED(19),

    INCORRECT_SSN_2(20),
    WEB_AUTH_NEEDED(21),
    DELETE_CHARACTER_FAILED_ON_GUILD_MASTER(22),
    NOT_AGREED_EULA(23),
    DELETE_CHARACTER_FAILED_ENGAGED(24),

    INCORRECT_SPW(20),
    SAME_PASSWORD_AND_SPW(22),
    SAME_PINCODE_AND_SPW(23),
    REGISTER_LIMITED_IP(25),
    REQUESTED_CHARACTER_TRANSFER(26),
    CASH_USER_CANNOT_USER_SIMPLE_CLIENT(27),
    DELETE_CHARACTER_FAILED_ON_FAMILY(29),
    INVALID_CHARACTER_NAME(30),
    INCORRECT_SSN(31),
    SSN_CONFIRM_FAILED(32),
    SSN_NOT_CONFIRMED(33),
    WORLD_TOO_BUSY(34),
    OTP_REISSUING(25),
    OTP_INFO_NOT_EXIST(26);

    private final int value;

    LoginResult(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }
}
