package kinoko.server.cashshop;

public enum CashItemResultType {
    // CashItemRes
    CharacterSaleSuccess(56),
    CharacterSaleFail(57),
    CharacterSaleInvalidName(58),
    CharacterSaleInvalidItem(59),

    ItemUpgradeSuccess(61),
    ItemUpgradeFail(62), // CashItemReq_ItemUpgradeFail
    ItemUpgradeDone(65),
    ItemUpgradeErr(66),

    VegaSuccess1(68),
    VegaSuccess2(69),
    VegaErr(70),
    VegaErr2(71),
    VegaErr_InvalidItem(72),
    VegaFail(73),

    CheckFreeCashItemTable_Done(79),
    CheckFreeCashItemTable_Failed(80),

    SetFreeCashItemTable_Done(82),
    SetFreeCashItemTable_Failed(83),

    LimitGoodsCount_Changed(84),
    WebShopOrderGetList_Done(85),
    WebShopOrderGetList_Failed(86),
    WebnShopReceive_Done(87),
    LoadLocker_Done(88),
    LoadLocker_Failed(89),
    LoadGift_Done(90),
    LoadGift_Failed(91),
    LoadWish_Done(92),
    LoadWish_Failed(93),
    MapleTV_Failed_Wrong_User_Name(94),
    MapleTV_Failed_User_Not_Connected(95),
    AvatarMegaphone_Queue_Full(96),
    AvatarMegaphone_Level_Limit(97),
    SetWish_Done(98),
    SetWish_Failed(99),
    Buy_Done(100),
    Buy_Failed(101),
    UseCoupon_Done(102),
    UseCoupon_Done_NormalItem(103),
    GiftCoupon_Done(104),
    UseCoupon_Failed(105),
    UseCoupon_CashItem_Failed(106),
    Gift_Done(107),
    Gift_Failed(108),
    IncSlotCount_Done(109),
    IncSlotCount_Failed(110),
    IncTrunkCount_Done(111),
    IncTrunkCount_Failed(112),
    IncCharSlotCount_Done(113),
    IncCharSlotCount_Failed(114),
    IncBuyCharCount_Done(115),
    IncBuyCharCount_Failed(116),
    EnableEquipSlotExt_Done(117),
    EnableEquipSlotExt_Failed(118),
    MoveLtoS_Done(119),
    MoveLtoS_Failed(120),
    MoveStoL_Done(121),
    MoveStoL_Failed(122),
    Destroy_Done(123),
    DestroyFailed(124),
    Expire_Done(125),
    Expire_Failed(126),
    Use_Done(127),
    Use_Failed(128),
    StatChange_Done(129),
    StatChange_Failed(130),
    SkillChange_Done(131),
    SkillChange_Failed(132),
    SkillReset_Done(133),
    SkillReset_Failed(134),
    DestroyPetItem_Done(135),
    DestroyPetItem_Failed(136),
    SetPetName_Done(137),
    SetPetName_Failed(138),
    SetPetLife_Done(139),
    SetPetLife_Failed(140),
    MovePetStat_Failed(141), // some of these are flipped
    MovePetStat_Done(142),
    SetPetSkill_Failed(143),
    SetPetSkill_Done(144),
    SendMemo_Done(145),
    SendMemo_Warning(146),
    SendMemo_Failed(147),
    GetMaplePoint_Done(148),
    GetMaplePoint_Failed(149),
    Rebate_Done(150),
    Rebate_Failed(151),
    Couple_Done(152),
    Couple_Failed(153),
    BuyPackage_Done(154),
    BuyPackage_Failed(155),
    GiftPackage_Done(156),
    GiftPackage_Failed(157),
    BuyNormal_Done(158),
    BuyNormal_Failed(159),
    ApplyWishlistEvent_Done(160),
    ApplyWishlistEvent_Failed(161),
    Friendship_Done(162),
    Friendship_Failed(163),
    LoadExceptionList_Done(164),
    LoadExceptionList_Failed(165),
    UpdateExceptionList_Done(166),
    UpdateExceptionList_Failed(167),
    LoadFreeCashItem_Done(168),
    LoadFreeCashItem_Failed(169),
    FreeCashItem_Done(170),
    FreeCashItem_Failed(171),
    Script_Done(172),
    Script_Failed(173),
    Bridge_Failed(174),
    PurchaseRecord_Done(175),
    PurchaseRecord_Failed(176),
    EvolPet_Failed(177),
    EvolPet_Done(178),
    NameChangeBuy_Done(179),
    NameChangeBuy_Failed(180),
    TransferWorld_Done(181),
    TransferWorld_Failed(182),
    CashGachaponOpen_Done(183),
    CashGachaponOpen_Failed(184),
    CashGachaponCopy_Done(185),
    CashGachapon_Copy_Failed(186),
    ChangeMaplePoint_Done(187),
    ChangeMaplePoint_Failed(188),

    Give_Done(190),
    GIve_Failed(191),
    GashItemGachapon_Failed(192), // [sic]
    CashItemGachapon_Done(193);


    private final int value;

    CashItemResultType(int value) {
        this.value = value;
    }

    public final int getValue() {
        return value;
    }
}
